#!/bin/bash

function s21_output {
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}HOSTNAME${ENDCOLOR} = ${TEXT_BACK_COLOR}${TEXT_COLOR}$HOSTNAME${ENDCOLOR}" 
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}TIMEZONE${ENDCOLOR} = ${TEXT_BACK_COLOR}${TEXT_COLOR}$TIMEZONE${ENDCOLOR}"
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}USER${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$USER${ENDCOLOR}"
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}OS${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$OS${ENDCOLOR}"
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}DATE${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$DATE${ENDCOLOR}" 
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}UPTIME${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$UPTIME${ENDCOLOR}" 
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}UPTIME_SEC${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$UPTIME_SEC${ENDCOLOR}" 
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}IP${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$IP${ENDCOLOR}"
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}MASK${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$MASK${ENDCOLOR}" 
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}GATEWAY${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$GATEWAY${ENDCOLOR}" 
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}RAM_TOTAL${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$RAM_TOTAL${ENDCOLOR}" 
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}RAM_USED${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$RAM_USED${ENDCOLOR}"
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}RAM_FREE${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$RAM_FREE${ENDCOLOR}"
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}SPACE_ROOT${ENDCOLOR}  = ${TEXT_BACK_COLOR}${TEXT_COLOR}$SPACE_ROOT${ENDCOLOR}" 
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}SPACE_ROOT_USED${ENDCOLOR} = ${TEXT_BACK_COLOR}${TEXT_COLOR}$SPACE_ROOT_USED${ENDCOLOR}" 
  echo -e "${HEAD_BACK_COLOR}${HEAD_COLOR}SPACE_ROOT_FREE${ENDCOLOR} = ${TEXT_BACK_COLOR}${TEXT_COLOR}$SPACE_ROOT_FREE${ENDCOLOR}"
}